id: P008061
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:58:47.217526
source_metadata:
  id: bdr:W1AC275
  title: 'ང་ཚོ་སྤྲིན་བཞིན་འཕྱོ། '
  author: ''
  volumes:
    a3cf607e24154782bd956cc45fc0d7e1:
      image_group_id: I2PD20341
      title: Volume 1 of nga tsho sprin bzhin 'phyo/
      volume_number: 1
      total_pages: 354
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
