id: P008061
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC275
  title: 'ང་ཚོ་སྤྲིན་བཞིན་འཕྱོ། '
  author: ''
  volumes:
    0358bd3a673d4cfcb640e15530590502:
      image_group_id: I2PD20341
      title: ''
      volume_number: 1
      total_pages: 354
ebook_metadata:
  title: 'ང་ཚོ་སྤྲིན་བཞིན་འཕྱོ། '
  author: ''
  sku: P008061
  cover: cover.jpg
  layers:
  - pagination
